apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: my-container
          image: karimshan/docker-repo:latest
          ports:
            - containerPort: 3001
          command: [ "npm", "start" ]

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30000
